### ISSUE TITLE
Suggestion to use callbacks to set meteor connection and user data into store

### ISSUE THREAD

**Issue by ujwal-setlur** [swhamilton/react-native-navigation-redux-meteor#1]
Your example was very useful for me. Thank you very much. I see your code does not yet put meteor data into the store, and that is something I struggled with as well. After reading through the react-native-meteor code, I think the following should work:

```
    console.log("Connecting to Meteor port at " + meteorURL);
    Meteor.connect(meteorURL);
    let Data = Meteor.getData();
    // set callbacks for connect/disconnect events
    Data.ddp.on("connected", () => {
      console.log("We are connected!!!");
      // we could dispatch an action to the store here
    });
    Data.ddp.on("disconnected", () => {
      console.log("We are disconnected!!!");
      // we could dispatch an action to the store here
    });
   // callback for onLogin event -- called by loginWithToken()
    Data.on("onLogin", () => {
      console.log("We are logged in!!");
      // we could dispatch an action to the store here
    });
```

Thoughts?

**Comment by swhamilton** [comment]
Thanks @ujwal-setlur for the example. That looks correct however it's been about 2 years since I originally used this library and have since moved to using Apollo/GraphQL, so I don't have reason to try it out at this time and give feedback.

But again, appreciate the feedback and we'll keep this around so others can find it useful!

**Comment by ujwal-setlur** [comment]
Yeah, I am considering Apollo/GraphQL myself. I just wanted to record this for posterity 😀
